version: '3.5'


services:
    faber-agent:
        
        ports:
            - "8021:8021"
            - "8022:8022"
        
        expose:
            - "8021"
            - "8022"

        networks:
            testing_net:
                ipv4_address: 172.22.0.101
        
        entrypoint: /bin/bash
        command: [
            "-c",
            "sleep 14;
                aca-py start \
                    --label faber \
                    --inbound-transport http 172.22.0.101 8021 \
                    --genesis-file demo/kiva/test/pool_transactions_genesis \
                    --admin 172.22.0.101 8022  \
                    --admin-insecure-mode \
                    --outbound-transport http \
                    --log-level debug \
                    --webhook-url https://e7a1d16b6a8ec36fa3fd461350e61c8c.m.pipedream.net \
                    --endpoint http://172.22.0.101:8021 \
                    --wallet-type indy \
                    --seed ${TRUSTEE_SEED} \
                    --replace-public-did \
                    --auto-accept-invites \
                    --auto-accept-requests \
                    --auto-respond-messages \
                    --auto-respond-credential-offer \
                    --auto-store-credential \
                    --auto-respond-presentation-request \
                    --auto-respond-presentation-proposal \
                    --auto-verify-presentation \
                    --preserve-exchange-records",
        ]

        volumes:
            - /aries_cloudagent
            - /demo

        # # entrypoint: /bin/bash
        build:
            context: .
            dockerfile: docker/Dockerfile.demo
        
        
    alice-agent:
       
        
        networks:
                testing_net:
                    ipv4_address: 172.22.0.100
                

        ports:
            - "8031:8031"
            - "8032:8032"
            - "5001:5001"
        expose:
            - "8031"
            - "8032"
            - "5001"
        
        entrypoint: /bin/bash
        command: [
            "-c",
            "sleep 14;
                aca-py start \
                    --label alice \
                    --inbound-transport http 172.22.0.100 8031 \
                    --genesis-file demo/kiva/test/pool_transactions_genesis \
                    --admin 172.22.0.100 8032  \
                    --admin-insecure-mode \
                    --outbound-transport http \
                    --log-level debug \
                    --webhook-url https://e7a1d16b6a8ec36fa3fd461350e61c8c.m.pipedream.net \
                    --endpoint http://172.22.0.100:8031 \
                    --wallet-type indy \
                    --auto-accept-invites \
                    --auto-accept-requests \
                    --auto-respond-messages \
                    --auto-respond-credential-offer \
                    --auto-store-credential \
                    --auto-respond-presentation-request \
                    --auto-respond-presentation-proposal \
                    --auto-verify-presentation \
                    --preserve-exchange-records",
        ]

        volumes:
            - /aries_cloudagent
            - /demo
        # # entrypoint: /bin/bash
        build:
            context: .
            dockerfile: docker/Dockerfile.demo
volumes:
  .:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16